- name: configure backend
  hosts: backend
  become: yes
  tasks:
  - name: disabiling default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabliling nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: latest

  - name: create the user
    ansible.builtin.user:
      name: expense